#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), "..", "lib")

require "release/notes"

rails_config_file = "./config/initializers/release_notes.rb"
config_file = "./config/release_notes.rb"

file = File.exist?(rails_config_file) ? rails_config_file : config_file

begin
  require file
  Release::Notes::Cmd.start(ARGV)
rescue LoadError
  warn "=> Missing release_notes.rb configuration file"
rescue SignalException => e
  # We might receive SIGTERM before our signal handler is installed.
  if Signal.signame(e.signo) == "TERM"
    exit(0)
  else
    raise
  end
rescue
  exit(1)
else
  exit(0)
end
