name: Ruby

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5.x', '2.6.x']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Bundle
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
    - name: Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    - name: Test
      run: bundle exec rspec
    - name: Rubocop
      run: bundle exec rubocop
    - name: Code Climate
      if: success()
      run: bundle exec codeclimate-test-reporter
